name: Pull Requests

on:
  pull_request:
    branches:
      - develop

jobs:
  tests:
    uses: cfsimplicity/spreadsheet-cfml/.github/workflows/tests.yml@develop
  tests-java-11:
    uses: cfsimplicity/spreadsheet-cfml/.github/workflows/tests-java-11.yml@develop