name: Run test suite

on:
  workflow_dispatch:

jobs:
 testbox:
    runs-on: ubuntu-latest
    # testbox uses encodeForHTML so we need that extension installed
    env:
        LUCEE_EXTENSIONS: "37C61C0A-5D7E-4256-8572639BE0CF5838"
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11
    - name: Setup CommandBox
      uses: Ortus-Solutions/setup-commandbox@main
    - name: Install dependencies
      run: box install testbox
    - name: Start a server
      run: box server start cfengine=lucee@5
    - name: Run TestBox Tests
      run: box testbox run "http://localhost:8080/test/index.cfm"
